Update scripts

diff --git a/CARStech/bin/backups b/CARStech/bin/backups
--- a/CARStech/bin/backups
+++ b/CARStech/bin/backups
@@ -1,72 +1,33 @@
 #!/bin/bash
 
-#Este script realizara copias de las siguientes carpetas: /var/www/ /etc/nginx /etc/ssh /home
+#Este script realizara copias de las siguientes carpetas: /var/www /etc/nginx /etc/ssh /home /etc/bind /etc/dhcpd
 #FTP Credentials
 serverAddress=
-folderBackup=$(hostname)
 username=
 password=
 port=21
 
-doBackup() {
-    filename=backup-$(date +%Y-%m-%d).tar.gz
-    tar czf "$filename" /home/
+# Backup Directory
+backupDir="/tmp/backups"
+mkdir -p "$backupDir"
+filename="$backupDir/backup-$(hostname)-$(date +%Y-%m-%d).tar.gz"
+logFile="$backupDir/registro_backups.log"
+
+log() {
+    echo "$(date +'%Y-%m-%d %H:%M:%S') - $1" >> "$logFile"
+}
+
+tar czPf "$filename" /var/www /etc/nginx /etc/ssh /home /etc/bind /etc/dhcpd
+if [ $? -eq 0 ]; then
+    log "Archivo $filename creado con exito."
+
+    curl -T "$filename" ftp://$serverAddress:$port/StorageVR/ --user $username:$password
     if [ $? -eq 0 ]; then
-        read -p "¿Desea subir la copia de seguridad al servidor FTP configurado? Y/N  :" question
-        if [ "$question" == "Y" ]; then
-            curl -T "$filename" ftp://$serverAddress --user $username:$password
-            if [ $? -eq 0 ]; then
-                rm $filename
-                read -p "Se ha subido el archivo con exito, presione enter para continuar"
-            fi
-        else
-            read -p "Operacion cancelada, presione enter para volver"
-        fi
+        log "Subido correctamente a $serverAddress."
+        rm "$filename"
     else
-        read -p "Ha ocurrido un error al generar el archivo, se debe realizar la copia manualmente"
+        log "Error: No se ha podido subir la copia de seguridad al servidor"
     fi
-    clear
-}
-
-listBackups() {
-        curl ftp://$serverAddress/ --user $username:$password
-}
-
-delBackup() {
-        read -p "Introduce el nombre del archivo completo obtenido a traves de Listar copias de seguridad: " deleteThisBackup
-        if [ "$deleteThisBackup" != "" ]; then
-            
-        fi
-}
-
-clear
-menu() {
-    echo "COPIAS DE SEGURIDAD"
-    echo "Selecciona una opcion:"
-    echo "1) Realizar Copia de seguridad"
-    echo "2) Listar copias de seguridad"
-    echo "3) Eliminar copia de seguridad"
-    echo "4) Salir"
-    read -p "Introduce el número de tu opción: " option
-
-    case $option in
-        1) selected="Realizar Copia de seguridad";;
-        2) selected="Listar copias de seguridad";;
-        3) selected="Eliminar copia de seguridad";;
-        4) selected="Salir";;
-        *) echo "Opción no válida"; selected="";;
-    esac
-}
-
-menu
-
-while [ "$selected" != "Salir" ]
-do
-    case $selected in
-        "Realizar Copia de seguridad") doBackup;;
-        "Listar copias de seguridad") listBackups;;
-        "Eliminar copia de seguridad") delBackup;;
-        "Salir") break;;
-    esac
-    menu
-done
+else
+    log "Error: Error al crear el archivo de backup."
+fi
